version: "2.2.3"
services:
  #MySQL Database
  MySQL-database:
    image: mysql:8.0
    container_name: MYSQL-db
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /var/lib/docker/volumes/mysql-db-volume/_data:/var/lib/mysql

  #PPM-TOOL APP
  app:
    depends_on:
      - MySQL-database
    build:
      context: .
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.datasource.url": "jdbc:mysql://MySQL-database:3306/ppm-tool?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.show-sql": "true",
        "spring.jpa.properties.hibernate.format-sql": "true"
       }'
    ports:
      - 8080:8080